# Generated by Django 3.1 on 2020-08-13 06:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200813_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_style',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profilePic.png', null=True, upload_to=accounts.models.path_and_rename),
        ),
    ]
