# Generated by Django 3.0.8 on 2020-08-04 11:27

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='num_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(upload_to=links.models.path_and_rename),
        ),
    ]
