# Generated by Django 3.1 on 2020-08-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20200804_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Click',
        ),
    ]
